# C\u00e1\u00ba\u00a5u h\u00c3\u00acnh g\u00e1\u00bb\u00adi mail (d\u00e1\u00bb\u00b1 \u00c3\u00a1n h\u00e1\u00bb\u008dc - d\u00c3\u00b9ng Gmail)
# Gmail: b\u00e1\u00ba\u00adt x\u00c3\u00a1c minh 2 b\u00c6\u00b0\u00e1\u00bb\u009bc, t\u00e1\u00ba\u00a1o "App Password" t\u00e1\u00ba\u00a1i https://myaccount.google.com/apppasswords
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.from=averiscosmetics@gmail.com
mail.password=utme vyeh vzgy jgeb
